global using Lagoon.Core.Exceptions;
global using Lagoon.Helpers;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.JSInterop;
global using System.Collections.Generic;
global using System.Net.Http;
global using System.Threading.Tasks;
global using System;
